// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCCEcoCria.Data;

#nullable disable

namespace ECOCRIA.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240920183452_PontosMateriais")]
    partial class PontosMateriais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.ColetaItens", b =>
                {
                    b.Property<int>("IdItemColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItemColeta"));

                    b.Property<int?>("IdColeta")
                        .HasColumnType("int");

                    b.Property<int?>("IdMaterial")
                        .HasColumnType("int");

                    b.Property<int?>("IdOrdemGrandeza")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeColeta")
                        .HasColumnType("int");

                    b.HasKey("IdItemColeta");

                    b.HasIndex("IdColeta");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdOrdemGrandeza");

                    b.ToTable("TB_COLETAITENS", (string)null);

                    b.HasData(
                        new
                        {
                            IdItemColeta = 1,
                            QuantidadeColeta = 1
                        },
                        new
                        {
                            IdItemColeta = 2,
                            QuantidadeColeta = 2
                        },
                        new
                        {
                            IdItemColeta = 3,
                            QuantidadeColeta = 1
                        },
                        new
                        {
                            IdItemColeta = 4,
                            QuantidadeColeta = 2
                        },
                        new
                        {
                            IdItemColeta = 5,
                            QuantidadeColeta = 1
                        },
                        new
                        {
                            IdItemColeta = 6,
                            QuantidadeColeta = 2
                        },
                        new
                        {
                            IdItemColeta = 7,
                            QuantidadeColeta = 1
                        });
                });

            modelBuilder.Entity("Models.Coletas", b =>
                {
                    b.Property<int>("IdColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColeta"));

                    b.Property<int?>("IdPonto")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("MomentoColeta")
                        .HasColumnType("datetime2");

                    b.HasKey("IdColeta");

                    b.HasIndex("IdPonto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_COLETAS", (string)null);

                    b.HasData(
                        new
                        {
                            IdColeta = 1,
                            MomentoColeta = new DateTime(2024, 9, 20, 15, 34, 51, 394, DateTimeKind.Local).AddTicks(6752)
                        },
                        new
                        {
                            IdColeta = 2,
                            MomentoColeta = new DateTime(2024, 9, 20, 15, 34, 51, 394, DateTimeKind.Local).AddTicks(6762)
                        },
                        new
                        {
                            IdColeta = 3,
                            MomentoColeta = new DateTime(2024, 9, 20, 15, 34, 51, 394, DateTimeKind.Local).AddTicks(6763)
                        },
                        new
                        {
                            IdColeta = 4,
                            MomentoColeta = new DateTime(2024, 9, 20, 15, 34, 51, 394, DateTimeKind.Local).AddTicks(6764)
                        },
                        new
                        {
                            IdColeta = 5,
                            MomentoColeta = new DateTime(2024, 9, 20, 15, 34, 51, 394, DateTimeKind.Local).AddTicks(6766)
                        },
                        new
                        {
                            IdColeta = 6,
                            MomentoColeta = new DateTime(2024, 9, 20, 15, 34, 51, 394, DateTimeKind.Local).AddTicks(6767)
                        },
                        new
                        {
                            IdColeta = 7,
                            MomentoColeta = new DateTime(2024, 9, 20, 15, 34, 51, 394, DateTimeKind.Local).AddTicks(6768)
                        });
                });

            modelBuilder.Entity("Models.Comentarios", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<DateTime>("MomentoComentario")
                        .HasColumnType("datetime2");

                    b.Property<string>("TextoComentario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.HasKey("IdComentario");

                    b.ToTable("TB_COMENTARIOS", (string)null);
                });

            modelBuilder.Entity("Models.Materiais", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<int>("Material")
                        .HasColumnType("int");

                    b.Property<string>("NomeMaterial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.HasKey("IdMaterial");

                    b.ToTable("TB_MATERIAIS", (string)null);

                    b.HasData(
                        new
                        {
                            IdMaterial = 1,
                            Material = 1,
                            NomeMaterial = "Garrafa Pet"
                        },
                        new
                        {
                            IdMaterial = 2,
                            Material = 4,
                            NomeMaterial = "Papelão"
                        },
                        new
                        {
                            IdMaterial = 3,
                            Material = 1,
                            NomeMaterial = "Saco Plástico"
                        },
                        new
                        {
                            IdMaterial = 4,
                            Material = 2,
                            NomeMaterial = "Lata de Feijoada"
                        },
                        new
                        {
                            IdMaterial = 5,
                            Material = 2,
                            NomeMaterial = "Latinha"
                        },
                        new
                        {
                            IdMaterial = 6,
                            Material = 1,
                            NomeMaterial = "Garrafa Pet"
                        },
                        new
                        {
                            IdMaterial = 7,
                            Material = 3,
                            NomeMaterial = "Jarra de Vidro"
                        });
                });

            modelBuilder.Entity("Models.OrdemDeGrandeza", b =>
                {
                    b.Property<int>("IdOrdemGrandeza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdemGrandeza"));

                    b.Property<string>("DescricaoOrdemGrandeza")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.HasKey("IdOrdemGrandeza");

                    b.ToTable("TB_ORDEMGRANDEZA", (string)null);
                });

            modelBuilder.Entity("Models.Parceiros", b =>
                {
                    b.Property<int>("IdParceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParceiro"));

                    b.Property<DateTime>("DataDoacao")
                        .HasColumnType("datetime2");

                    b.Property<double>("DoacaoParceiro")
                        .HasColumnType("float");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NomeParceiro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<bool>("StatusParceiro")
                        .HasColumnType("bit");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdParceiro");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("TB_PARCEIROS", (string)null);

                    b.HasData(
                        new
                        {
                            IdParceiro = 1,
                            DataDoacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoacaoParceiro = 500.0,
                            NomeParceiro = "Empresa BlaBla",
                            StatusParceiro = false
                        },
                        new
                        {
                            IdParceiro = 2,
                            DataDoacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoacaoParceiro = 500.0,
                            NomeParceiro = "Market Empresa",
                            StatusParceiro = false
                        },
                        new
                        {
                            IdParceiro = 3,
                            DataDoacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoacaoParceiro = 500.0,
                            NomeParceiro = "Empresa Eletro",
                            StatusParceiro = false
                        },
                        new
                        {
                            IdParceiro = 4,
                            DataDoacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoacaoParceiro = 500.0,
                            NomeParceiro = "Empresa Papel",
                            StatusParceiro = false
                        },
                        new
                        {
                            IdParceiro = 5,
                            DataDoacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoacaoParceiro = 500.0,
                            NomeParceiro = "Empresa Rainiken",
                            StatusParceiro = false
                        },
                        new
                        {
                            IdParceiro = 6,
                            DataDoacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoacaoParceiro = 500.0,
                            NomeParceiro = "Empresa squol",
                            StatusParceiro = false
                        },
                        new
                        {
                            IdParceiro = 7,
                            DataDoacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoacaoParceiro = 500.0,
                            NomeParceiro = "Empresa suifiti",
                            StatusParceiro = false
                        });
                });

            modelBuilder.Entity("Models.Pontos", b =>
                {
                    b.Property<int>("IdPonto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPonto"));

                    b.Property<int>("CepEndereco")
                        .HasColumnType("int");

                    b.Property<string>("CidadeEndereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("EnderecoPonto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<int?>("IdTipoPonto")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("NomePonto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("UfEndereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.HasKey("IdPonto");

                    b.HasIndex("IdTipoPonto")
                        .IsUnique();

                    b.ToTable("TB_PONTOS", (string)null);

                    b.HasData(
                        new
                        {
                            IdPonto = 1,
                            CepEndereco = 1986,
                            CidadeEndereco = "São Paulo",
                            EnderecoPonto = "Rua São Quirino, 468 - Vila Guilherme",
                            IdTipoPonto = 1,
                            NomePonto = "São Quirino Sucatas",
                            UfEndereco = "SP"
                        },
                        new
                        {
                            IdPonto = 2,
                            CepEndereco = 2995,
                            CidadeEndereco = "São Paulo",
                            EnderecoPonto = "R. Santa Clara, 350 - Brás",
                            IdTipoPonto = 2,
                            NomePonto = "Reciclagem, Sucatas e Aparas Farpec",
                            UfEndereco = "SP"
                        },
                        new
                        {
                            IdPonto = 3,
                            CepEndereco = 2995,
                            CidadeEndereco = "São Paulo",
                            EnderecoPonto = "R. Dr. Miguel Paulo Capalbo, 75 - Pari",
                            IdTipoPonto = 3,
                            NomePonto = "Helio & Richard Reciclagem",
                            UfEndereco = "SP"
                        },
                        new
                        {
                            IdPonto = 4,
                            CepEndereco = 2054,
                            CidadeEndereco = "São Paulo",
                            EnderecoPonto = "Rua José Bernardo Pinto, 1480 - Vila Guilherme",
                            IdTipoPonto = 4,
                            NomePonto = "Ecoponto Vila Guilherme",
                            UfEndereco = "SP"
                        },
                        new
                        {
                            IdPonto = 5,
                            CepEndereco = 2103,
                            CidadeEndereco = "São Paulo",
                            EnderecoPonto = "Av. Guilherme Cotching, 726 - Vila Maria Baixa",
                            IdTipoPonto = 5,
                            NomePonto = "Latasa Reciclagem",
                            UfEndereco = "SP"
                        },
                        new
                        {
                            IdPonto = 6,
                            CepEndereco = 2004,
                            CidadeEndereco = "São Paulo",
                            EnderecoPonto = "R. Henrique Felipe da Costa, 650 - Vila Guilherme",
                            IdTipoPonto = 6,
                            NomePonto = "Ciclopel Com de Aparas de Papel",
                            UfEndereco = "SP"
                        },
                        new
                        {
                            IdPonto = 7,
                            CepEndereco = 2104,
                            CidadeEndereco = "São Paulo",
                            EnderecoPonto = "R. Eli, 190 - Vila Maria Baixa",
                            IdTipoPonto = 7,
                            NomePonto = "COLETATEC",
                            UfEndereco = "SP"
                        });
                });

            modelBuilder.Entity("Models.PontoseMateriais", b =>
                {
                    b.Property<string>("DescricaoPontomaterial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<int>("IdPontoMaterial")
                        .HasColumnType("int");

                    b.Property<bool>("StatusPontoMaterial")
                        .HasColumnType("bit");

                    b.ToTable("TB_PONTOSMATERIAIS", (string)null);
                });

            modelBuilder.Entity("Models.Pontuacao", b =>
                {
                    b.Property<int>("QuantidadePontos")
                        .HasColumnType("int");

                    b.Property<bool>("StatusPontos")
                        .HasColumnType("bit");

                    b.ToTable("TB_PONTUACAO", (string)null);
                });

            modelBuilder.Entity("Models.Premios", b =>
                {
                    b.Property<int>("IdPremio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPremio"));

                    b.Property<string>("DescricaoPremio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<int>("PontosPremio")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadePremio")
                        .HasColumnType("int");

                    b.HasKey("IdPremio");

                    b.ToTable("TB_PREMIOS", (string)null);
                });

            modelBuilder.Entity("Models.Publicacao", b =>
                {
                    b.Property<int>("IdPublicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPublicacao"));

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TextoPublicacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<string>("TituloPublicacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.HasKey("IdPublicacao");

                    b.ToTable("TB_PUBLICACAO", (string)null);
                });

            modelBuilder.Entity("Models.TipoDePonto", b =>
                {
                    b.Property<int>("IdTipoPonto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoPonto"));

                    b.Property<string>("DescricaoTipoPonto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<bool>("StatusTipoPonto")
                        .HasColumnType("bit");

                    b.HasKey("IdTipoPonto");

                    b.ToTable("TB_TIPOPONTO", (string)null);

                    b.HasData(
                        new
                        {
                            IdTipoPonto = 1,
                            DescricaoTipoPonto = "Ferro velho em geral",
                            StatusTipoPonto = false
                        },
                        new
                        {
                            IdTipoPonto = 2,
                            DescricaoTipoPonto = "Reciclagem",
                            StatusTipoPonto = false
                        },
                        new
                        {
                            IdTipoPonto = 3,
                            DescricaoTipoPonto = "Reciclagem em geral",
                            StatusTipoPonto = false
                        },
                        new
                        {
                            IdTipoPonto = 4,
                            DescricaoTipoPonto = "Ecoponto",
                            StatusTipoPonto = false
                        },
                        new
                        {
                            IdTipoPonto = 5,
                            DescricaoTipoPonto = "Recilagem de metais",
                            StatusTipoPonto = false
                        },
                        new
                        {
                            IdTipoPonto = 6,
                            DescricaoTipoPonto = "Recilcagem de papel e celulose",
                            StatusTipoPonto = false
                        },
                        new
                        {
                            IdTipoPonto = 7,
                            DescricaoTipoPonto = "Recilcagem ",
                            StatusTipoPonto = false
                        });
                });

            modelBuilder.Entity("Models.Trocas", b =>
                {
                    b.Property<int>("IdTroca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTroca"));

                    b.Property<DateTime>("MomentoTroca")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTroca");

                    b.ToTable("TB_TROCAS", (string)null);
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("Varchar")
                        .HasDefaultValue("Cliente");

                    b.HasKey("IdUsuario");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            EmailUsuario = "seuEmail@gmail.com",
                            Latitude = -23.520024100000001,
                            Longitude = -46.596497999999997,
                            NomeUsuario = "admin",
                            PasswordHash = new byte[] { 34, 238, 215, 34, 199, 62, 72, 156, 217, 143, 47, 189, 220, 148, 153, 172, 27, 98, 229, 146, 162, 19, 156, 163, 172, 226, 169, 123, 164, 63, 160, 205, 136, 38, 34, 125, 52, 68, 37, 167, 161, 191, 1, 249, 58, 217, 178, 232, 68, 245, 229, 204, 118, 122, 251, 47, 225, 184, 77, 121, 125, 200, 9, 56, 237, 114, 48, 127, 57, 22, 10, 145, 150, 230, 222, 77, 93, 213, 81, 130, 86, 229, 165, 108, 190, 108, 166, 186, 63, 166, 151, 147, 148, 243, 182, 94, 223, 114, 19, 54, 170, 15, 149, 3, 119, 251, 238, 233, 211, 43, 59, 80, 51, 246, 249, 72, 192, 113, 207, 29, 1, 164, 90, 137, 67, 183, 122, 87 },
                            Perfil = "Admin"
                        });
                });

            modelBuilder.Entity("Models.ColetaItens", b =>
                {
                    b.HasOne("Models.Coletas", "Coletas")
                        .WithMany("ColetaItens")
                        .HasForeignKey("IdColeta")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Models.Materiais", "Materiais")
                        .WithMany("ColetaItens")
                        .HasForeignKey("IdMaterial");

                    b.HasOne("Models.OrdemDeGrandeza", "OrdemDeGrandeza")
                        .WithMany("ColetaItens")
                        .HasForeignKey("IdOrdemGrandeza");

                    b.Navigation("Coletas");

                    b.Navigation("Materiais");

                    b.Navigation("OrdemDeGrandeza");
                });

            modelBuilder.Entity("Models.Coletas", b =>
                {
                    b.HasOne("Models.Pontos", "Pontos")
                        .WithMany("Coletas")
                        .HasForeignKey("IdPonto");

                    b.HasOne("Models.Usuario", "Usuario")
                        .WithMany("Coletas")
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Pontos");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Models.Parceiros", b =>
                {
                    b.HasOne("Models.Usuario", "Usuario")
                        .WithMany("Parceiros")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Models.Pontos", b =>
                {
                    b.HasOne("Models.TipoDePonto", "TipoDePonto")
                        .WithOne("Pontos")
                        .HasForeignKey("Models.Pontos", "IdTipoPonto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDePonto");
                });

            modelBuilder.Entity("Models.Coletas", b =>
                {
                    b.Navigation("ColetaItens");
                });

            modelBuilder.Entity("Models.Materiais", b =>
                {
                    b.Navigation("ColetaItens");
                });

            modelBuilder.Entity("Models.OrdemDeGrandeza", b =>
                {
                    b.Navigation("ColetaItens");
                });

            modelBuilder.Entity("Models.Pontos", b =>
                {
                    b.Navigation("Coletas");
                });

            modelBuilder.Entity("Models.TipoDePonto", b =>
                {
                    b.Navigation("Pontos");
                });

            modelBuilder.Entity("Models.Usuario", b =>
                {
                    b.Navigation("Coletas");

                    b.Navigation("Parceiros");
                });
#pragma warning restore 612, 618
        }
    }
}
